name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      SourceServer:
        description: Source Server
        required: true
      SourcePort:
        description: Source Port
        required: false
      DestinationServer:
        description: Destination Server
        required: true
      DestinationPort:  
        description: Destination Port
        required: false
jobs:
  Semarchy_CICD:
    name: Semarchy CICD
    runs-on: ubuntu-latest
    steps:
        - name: Bump Package Version
          run:  echo "The source server is ${{ github.event.inputs.SourceServer }} , server port is ${{ github.event.inputs.SourcePort }} and Destination Server is  ${{ github.event.inputs.DestinationServer }},  Destination Port is  ${{ github.event.inputs.DestinationPort }} " 
        - name: setup python
          uses: actions/setup-python@v2
          with:
             python-version: 3.8
