name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
        - name: Bump Package Version
          run:  echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        - run:  echo  ${{ github.event.inputs.version }}
