name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      SourceServer:
        description: Source Server
        default: devsemarchy.eastus.cloudapp.azure.com
        required: true
      SourcePort:
        description: Source Port
        required: false
      DestinationServer:
        description: Destination Server
        default: prodsemarchy.eastus.cloudapp.azure.com
        required: true
      DestinationPort:  
        description: Destination Port
        required: false
jobs:
  Semarchy_CICD:
    name: Semarchy CICD
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v2
     - name: Create folder with todays date
       run: |
          mkdir "$(date +"%d-%m-%Y")" && cd $_
          touch .gitkeep
     - name: setup python
       uses: actions/setup-python@v2
       with:
           python-version: 3.8
     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
     - name: execute python script
       run: |
        python ./pythonscripts/WrapperSemarchyadmin.py export CustomerB2CDemo devsemarchy.eastus.cloudapp.azure.com ""
     #- name: Commit files
       #run: |
        #git add .
        #git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        #git config --local user.name "github-actions[bot]"
        #git commit -m "Add changes" -a
     #- name: Push changes
       #uses: ad-m/github-push-action@master
       #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #branch: ${{ github.ref }}
          
